# How to improve numpy skills 
1. Kaggle
Details: Kaggle offers Python and Data Science courses with practical exercises, including specific sections on NumPy. You can also find various notebooks by the community to learn advanced techniques.
Link: Kaggle - Python and Data Science Courses
2. DataCamp
Details: DataCamp provides interactive courses focused on Python, Data Science, and Machine Learning. It has a dedicated section for NumPy, including exercises and quizzes.
Link: DataCamp
3. W3Schools - NumPy Tutorial
Details: Offers beginner-friendly tutorials along with small quizzes to test your understanding of different topics in NumPy.
Link: W3Schools - NumPy
4. LeetCode - Python Challenges
Details: While not specifically focused on NumPy, LeetCode's Python challenges often require the use of NumPy functions. It is a good place to solve problems and see how NumPy can be applied to solve them.
Link: LeetCode
5. NumPy Official Documentation
Details: The official NumPy documentation offers tutorials and a NumPy reference guide. It includes exercises ranging from beginner to advanced levels.
Link: NumPy Documentation
6. Practice Python with NumPy by Dataquest
Details: Dataquest offers free and paid courses. The Python for Data Science path includes NumPy exercises with a focus on practical applications.
Link: Dataquest
7. Hackerrank - Python (NumPy)
Details: Hackerrank has Python challenges, including specific problems related to NumPy arrays, matrices, and operations.
Link: Hackerrank
8. StrataScratch
Details: Provides a collection of real-world data science problems where you can practice NumPy along with other data manipulation libraries.
Link: StrataScratch
9. Google Colab and Kaggle Datasets
Details: You can explore datasets on Kaggle and Google Colab to practice manipulating data with NumPy.
Link: Kaggle Datasets
10. GitHub Repositories
Details: Search for GitHub repositories like NumPy exercises or Python Data Science Exercises, where you can find collections of NumPy problems with solutions.
Example Repo: GitHub - NumPy Exercises
These platforms offer a mix of theoretical learning, practical exercises, and real-world challenges to enhance your NumPy skills.

In [1]:
import numpy as np 

In [2]:
kanto = [76,134,50]
weight = [0.2,0.3,0.4]

In [5]:
def crop_yield(name,weight):
    result = 0 
    for i in range(len(name)):
        result += name[i] * weight[i]
    return result

In [6]:
crop_yield(kanto,weight)

75.4

In [7]:
# Using numpy array

In [8]:
karachi = np.array([74,67,43])

In [9]:
type(karachi)

numpy.ndarray

In [10]:
w1,w2,w3 = 0.2,0.3,0.4
weights =  np.array([w1,w2,w3])

In [11]:
weights[0]

0.2

In [12]:
karachi[1]

67

In [13]:
# Above multiplication of two vectors and then doing sum can be replace with .dot()

In [14]:
np.dot(karachi,weight)

52.099999999999994

In [ ]:
# Alternative method using this numpy function
(karachi*weights).sum()

52.099999999999994

In [16]:
arr = (karachi*weights)

In [17]:
arr.sum()

52.099999999999994

In [19]:
# A comparison of dot products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [20]:
arr1 = list(range(10000000))
arr2 = list(range(10000000,20000000))


ar1 = np.array(arr1)
ar2 = np.array(arr2)

In [22]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2
result

CPU times: total: 2.47 s
Wall time: 2.49 s


833333233333335000000

In [24]:
%%time
np.dot(ar1, ar2)

CPU times: total: 0 ns
Wall time: 12 ms


690258880

# Multi-Dimensional Numpy Arrays 

In [25]:
climate_data = np.array([
    [76,77,78],
    [80,81,82],
    [83,84,85],
    [90,91,92]
])

In [26]:
climate_data

array([[76, 77, 78],
       [80, 81, 82],
       [83, 84, 85],
       [90, 91, 92]])

In [ ]:
# 2d array (Matrix)
climate_data.shape

(4, 3)

In [ ]:
# 1D Array(Vector)
weights.shape

(3,)

In [30]:
karachi.shape

(3,)

In [34]:
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [35]:
arr3.shape

(2, 2, 3)

In [36]:
# Matrix Multiplication
np.matmul(climate_data,weights)

array([69.5, 73.1, 75.8, 82.1])

In [37]:
climate_data @ weights

array([69.5, 73.1, 75.8, 82.1])

In [ ]:
# Working with CSV Data Files 

In [39]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x251a2beb4d0>)

In [40]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [41]:
weights = np.array([0.3, 0.2, 0.5])

In [42]:
yields = climate_data @ weights

In [43]:
yields.shape

(10000,)

In [44]:

climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [45]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [49]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yield_apples', 
           comments='')

In [53]:
# counting number of equal term 
# (arr1 == arr2).sum()

In [54]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [55]:
arr3[2,0,3]

23.0

In [58]:
arr3[2,0,3]

23.0

In [60]:
arr3[:3,1,1:4]

array([[14. , 15. , 19. ],
       [92. , 36. , 18. ],
       [18. , 19.5, 43. ]])

In [61]:
arr3[1,0:2,1:3]

array([[16., 17.],
       [92., 36.]])

In [63]:
arr3[0,0:2,-1]

array([14., 19.])

In [67]:
arr3[2,1,2:]

array([19.5, 43. ])

In [69]:
arr3[1:,1,1:]

array([[92. , 36. , 18. ],
       [18. , 19.5, 43. ]])

In [71]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [73]:
np.ones((3,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [75]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
np.random.rand(5)

array([0.25021932, 0.42872951, 0.21433357, 0.71994873, 0.23396613])

In [77]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [78]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [79]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])